[window]
decorations = "full"
dynamic_title = true
startup_mode = "Maximized"  

[font.normal]
family = "UDEV Gothic NF"
style = "Regular"

[font.bold]
family = "UDEV Gothic NF"
style = "Bold"

[font.italic]
family = "UDEV Gothic NF"
style = "Italic"

[colors.primary]
background = "#1e1e1e"
foreground = "#d4d4d4"


