#!/usr/bin/env bash

source .env

# mariadb -u root -p
cat > init-db.sql << EOF
CREATE DATABASE IF NOT EXISTS roundcube;
CREATE USER IF NOT EXISTS 'roundcube'@'%' IDENTIFIED BY '${ROUNDCUBE_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON roundcube.* TO 'roundcube'@'%';

CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'wordpress'@'%' IDENTIFIED BY '${WORDPRESS_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'%';

CREATE DATABASE IF NOT EXISTS nextcloud;
CREATE USER IF NOT EXISTS 'nextcloud'@'%' IDENTIFIED BY '${NEXTCLOUD_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON nextcloud.* TO 'nextcloud'@'%';

CREATE DATABASE IF NOT EXISTS n8n;
CREATE USER IF NOT EXISTS 'n8n'@'%' IDENTIFIED BY '${N8N_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON n8n.* TO 'n8n'@'%';

CREATE DATABASE IF NOT EXISTS firefly;
CREATE USER IF NOT EXISTS 'firefly'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON firefly.* TO 'firefly'@'%';

CREATE DATABASE IF NOT EXISTS shogi;
CREATE USER IF NOT EXISTS 'shogi'@'%' IDENTIFIED BY '${SHOGI_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON shogi.* TO 'shogi'@'%';
CREATE DATABASE IF NOT EXISTS shogi_shadow;
GRANT ALL PRIVILEGES ON shogi_shadow.* TO 'shogi'@'%';

CREATE DATABASE IF NOT EXISTS keycloak;
CREATE USER IF NOT EXISTS 'keycloak'@'%' IDENTIFIED BY '${KC_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON keycloak.* TO 'keycloak'@'%';

FLUSH PRIVILEGES;
EOF